Quick fix for Docker

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -73,14 +73,6 @@ RUN ln -s /home/$NAME/.platformio/penv/bin/pio /usr/local/bin/pio
 RUN ln -s /home/$NAME/.platformio/penv/bin/piodebuggdb /usr/local/bin/piodebuggdb
 USER $NAME
 
-# Dry run PlatformIO to install the necessary dependencies
-RUN git clone https://github.com/byu-agrobotics/agrobot_2.0.git
-# '|| true' is used to ignore errors on a pio command failure
-WORKDIR /home/$NAME/agrobot_2.0/firmware/teensy_pio
-RUN pio run -t upload || true
-WORKDIR /home/$NAME
-RUN rm -rf /home/$NAME/agrobot_2.0
-
 # Install the micro-ROS agent
 RUN mkdir microros_ws
 
@@ -99,6 +91,14 @@ RUN source /opt/ros/humble/setup.bash && source install/setup.bash && ros2 run m
 SHELL ["/bin/sh", "-c"]
 
 WORKDIR /home/$NAME
+
+# Dry run PlatformIO to install the necessary dependencies
+RUN git clone https://github.com/byu-agrobotics/agrobot_2.0.git
+# '|| true' is used to ignore errors on a pio command failure
+WORKDIR /home/$NAME/agrobot_2.0/firmware/teensy_pio
+RUN pio run -t upload || true
+WORKDIR /home/$NAME
+RUN rm -rf /home/$NAME/agrobot_2.0
 
 # Set up automatic ROS 2 sourcing and colorized output
 RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
